export enum Configuration {
  PORT = 'PORT',
  HOST = 'HOST',
  USERNAME = 'USERNAME',
  PASSWORD = 'PASSWORD',
  DATABASE = 'DATABASE',
  JWT_SECRET = 'JWT_SECRET',
  JWT_SECRET_CUSTOMER = 'JWT_SECRET_CUSTOMER',
  DB_TYPE = 'DB_TYPE',
  DB_PORT = 'DB_PORT',
  CLOUD_NAME = 'CLOUD_NAME',
  API_KEY = 'API_KEY',
  API_SECRET = 'API_SECRET',
  STRIPE_KEY = 'STRIPE_KEY'
}
